In [2]:
import numpy as np
import pandas as pd 
import random

## Pré-traitement des données et analyse des données

In [3]:
df_train = pd.read_csv("data/train.csv")
df_test = pd.read_csv("data/test.csv")

# On prend les labels

In [37]:
train_labels = np.array(df_train.iloc[:,-1]) #Y
train_labels

train_values = np.array(df_train.iloc[:,:-1]) #X
print(len(train_values))

44760

In [58]:
def split_dataset(dataset, split_ratio=0.8):
    """Permet de separer les données en jeux d'entrainement et de validation selon un pourcentage pour le jeu d'entrainement"""

    random.shuffle(dataset)  # Mélangez les données aléatoirement

    split_index = int(len(dataset) * split_ratio)

    train_set = dataset[:split_index]
    validation_set = dataset[split_index:]

    return train_set, validation_set


train_set, validation_set = split_dataset(np.array(df_train), split_ratio=0.8)

#Division des labels et des données
X_train = train_set[:,:-1]
Y_train = train_set[::,-1]
X_val = validation_set[:,:-1]
Y_val = validation_set[::,-1]


print("=============== NORMALISATION ==============")

def normalisation(data):
    moyenne = data.mean(axis=0)
    ecart_type = data.std(axis=0)

    # Normalisez les colonnes sélectionnées (Soustraction de la moyenne et division par l'écart type)
    data = (data - moyenne) / ecart_type

    return data

X_train[:,1:] = normalisation(X_train[:,1:])

colone = df_train.columns
print(colone[:-1])
df3 = pd.DataFrame(X_train, columns=colone[:-1])
df3

=============== NORMALISATION ==============
Index(['SNo', 'lat', 'lon', 'TMQ', 'U850', 'V850', 'UBOT', 'VBOT', 'QREFHT',
       'PS', 'PSL', 'T200', 'T500', 'PRECT', 'TS', 'TREFHT', 'Z1000', 'Z200',
       'ZBOT', 'time'],
      dtype='object')

,SNo,lat,lon,TMQ,U850,V850,UBOT,VBOT,QREFHT,PS,PSL,T200,T500,PRECT,TS,TREFHT,Z1000,Z200,ZBOT,time
0,1.0,1.031083,0.458799,3.557241,-10.629754,7.353479,-11.332709,-0.173768,1.969556,-7.064332,-7.089123,4.529158,2.779403,22.297750,1.076648,0.669194,-1.876884,0.897271,0.735611,0.444425
1,1.0,1.031083,0.458799,3.557241,-10.629754,7.353479,-11.332709,-0.173768,1.969556,-7.064332,-7.089123,4.529158,2.779403,22.297750,1.076648,0.669194,-1.876884,0.897271,0.735611,0.444425
2,3.0,1.020778,0.458799,3.698229,-7.307945,11.881304,-10.911349,6.104211,1.938534,-8.562577,-8.593651,5.428193,2.952000,23.104406,1.076648,0.604466,-1.880932,0.625753,0.653912,0.444425
3,2.0,1.031083,0.458799,3.557241,-10.629754,7.353479,-11.332709,-0.173768,1.969556,-7.064332,-7.089123,4.529158,2.779403,22.297750,1.076648,0.669194,-1.876884,0.897271,0.735611,0.444425
4,5.0,1.031083,0.468557,3.392946,-8.045555,8.697967,-9.233565,2.357342,1.971491,-5.930315,-5.941986,3.444943,2.491355,15.828369,1.112803,0.707082,-1.864335,0.771904,0.771646,0.444425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35803,14073.0,0.670417,-0.243765,0.478840,-0.745191,0.034248,0.605073,-1.180437,0.769645,-0.782788,-0.791009,0.493406,0.934148,-0.112073,0.434009,0.637094,-0.933708,0.687555,0.692471,0.099693
35804,34714.0,-1.256571,2.898259,-0.429343,3.381381,-0.114728,2.392112,0.773797,-0.811139,0.644120,0.640091,-1.237486,-1.993401,-0.127135,-2.359968,-1.964165,0.628869,-2.492070,-1.706775,0.118387
35805,35502.0,-1.277181,2.917775,-1.784920,2.398008,-0.478853,2.504801,-0.712352,-2.032752,1.014729,1.011788,0.594332,-1.994149,-0.126130,-2.880639,-2.578474,1.002698,-2.349690,-2.421723,-1.792635
35806,5421.0,-0.844381,-0.965845,0.393097,-0.439961,-0.376871,-0.152064,-0.081380,0.124558,0.111565,0.105972,-1.196211,0.010703,-0.092923,0.047833,0.253036,0.114352,-0.228536,0.253199,-0.510017
35807,18713.0,0.670417,-0.204734,0.781723,0.071419,0.605024,0.955063,-0.760101,0.879240,-0.921118,-0.929745,-0.553695,0.516202,-0.103410,0.788045,0.808156,-1.095105,0.358024,0.848551,-0.531998

In [48]:
df3.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,35808.000000,3.580800e+04,3.580800e+04,3.580800e+04,35808.000000,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04,3.580800e+04
mean,8904.063785,1.015968e-16,4.603606e-16,-1.087403e-16,0.000000,3.174901e-18,-2.920908e-16,-6.349801e-18,-2.389113e-16,-3.692409e-15,1.679522e-15,3.586447e-15,7.419743e-15,7.937251e-18,-1.120978e-14,1.196303e-14,-3.746383e-16,-1.410092e-14,-2.797881e-15,2.577186e-14
std,7884.805465,1.000014e+00,1.000014e+00,1.000014e+00,1.000014,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00,1.000014e+00
min,1.000000,-1.280699e+00,-9.784770e-01,-2.311702e+00,-10.782872,-4.398695e+00,-1.145081e+01,-3.868066e+00,-2.582456e+00,-8.586312e+00,-8.617489e+00,-3.470862e+00,-4.683321e+00,-1.277155e-01,-3.128308e+00,-3.484637e+00,-1.934095e+00,-4.919808e+00,-3.350069e+00,-1.781603e+00
25%,2401.000000,-9.824526e-01,-5.971865e-01,-8.425367e-01,-0.530294,-5.012207e-01,-5.307818e-01,-5.836993e-01,-7.765594e-01,-5.406013e-01,-5.332477e-01,-6.251389e-01,-3.831942e-01,-1.277152e-01,-6.388680e-01,-6.542667e-01,-6.294183e-01,-4.726662e-01,-6.938938e-01,-5.183535e-01
50%,6601.000000,-8.179031e-01,-2.452260e-01,4.511233e-02,-0.009977,-5.353689e-02,-2.382229e-02,-1.725318e-02,4.767553e-02,-1.481755e-02,-1.327151e-02,1.721236e-02,2.008466e-01,-1.145288e-01,5.899734e-02,1.031807e-01,-2.001204e-02,1.117859e-01,1.074918e-01,-2.106995e-01
75%,13657.000000,1.105269e+00,5.173551e-01,7.078759e-01,0.549792,3.626426e-01,5.871540e-01,5.191900e-01,8.716140e-01,5.173619e-01,5.147862e-01,6.796163e-01,6.587560e-01,-6.554235e-02,9.009621e-01,8.561212e-01,5.567108e-01,7.454071e-01,8.801238e-01,4.125396e-01
max,35345.000000,1.136122e+00,2.941972e+00,3.710607e+00,4.488976,1.162845e+01,2.522638e+00,7.097142e+00,1.982037e+00,3.931606e+00,3.937336e+00,5.420008e+00,2.953105e+00,2.393931e+01,1.568683e+00,1.903949e+00,4.224780e+00,1.783599e+00,1.691155e+00,2.306646e+00

In [23]:
mu = trainset[:,:2].mean(axis=0)
sigma  = trainset[:,:2].std(axis=0)
trainset[:,:2] = (trainset[:,:2] -mu)/sigma
testset[:,:2] = (testset[:,:2] -mu)/sigma

NameError: name 'trainset' is not defined

In [ ]:
valeurs_classification = df_train["Label"].unique()
valeurs_classification

array([1, 2, 0], dtype=int64)

In [ ]:
df_train.dtypes

SNo         int64
lat       float64
lon       float64
TMQ       float64
U850      float64
V850      float64
UBOT      float64
VBOT      float64
QREFHT    float64
PS        float64
PSL       float64
T200      float64
T500      float64
PRECT     float64
TS        float64
TREFHT    float64
Z1000     float64
Z200      float64
ZBOT      float64
time        int64
Label       int64
dtype: object

In [ ]:
df_train.describe()

,SNo,lat,lon,TMQ,U850,V850,UBOT,VBOT,QREFHT,PS,...,T200,T500,PRECT,TS,TREFHT,Z1000,Z200,ZBOT,time,Label
count,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,...,44760.000000,44760.000000,4.476000e+04,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,4.476000e+04,44760.000000
mean,22380.500000,-2.933507,269.270833,34.621980,-0.609818,-0.017271,-2.138797,-0.808013,0.014375,101553.676510,...,216.829335,264.355844,4.580801e-08,298.344652,296.923570,135.521651,12290.118668,65.384474,2.001878e+07,0.387332
std,12921.243361,22.906771,41.046619,12.765972,6.866391,4.307206,6.059180,4.786933,0.003951,544.619301,...,2.295840,3.463063,2.448857e-07,3.763268,3.998874,42.355824,129.311333,1.035777,3.169958e+04,0.764119
min,1.000000,-31.095176,229.062500,6.960679,-58.805229,-26.216906,-58.260475,-20.760452,0.004364,96611.601560,...,208.824249,249.146011,-4.400000e-23,289.330750,285.426666,63.335205,11718.249020,62.433594,1.996061e+07,0.000000
25%,11190.750000,-24.582790,241.875000,23.906342,-5.520361,-2.379751,-6.568208,-3.897676,0.011261,101161.437500,...,215.463791,262.966995,1.410000e-14,295.959228,294.304199,102.716108,12230.382810,64.672365,2.000091e+07,0.000000
50%,22380.500000,-3.872229,253.125000,34.779505,-1.707679,0.148625,-2.701227,-0.855717,0.014613,101528.492200,...,217.109589,265.177933,5.210000e-09,298.752502,297.352692,133.820953,12319.832030,65.482857,2.001093e+07,0.000000
75%,33570.250000,21.766623,277.187500,44.321056,3.546206,2.326534,1.663309,2.034851,0.017949,101873.328100,...,218.367691,266.811386,3.030000e-08,301.767212,300.476807,161.562851,12388.112300,66.329466,2.003072e+07,0.000000
max,44760.000000,24.054759,354.375000,80.641357,32.277344,58.060246,30.215387,31.106283,0.022366,103996.953100,...,229.172897,273.580810,1.440000e-05,303.869812,304.364197,328.123688,12495.289060,67.131653,2.009102e+07,2.000000

array([1, 2, 0], dtype=int64)

In [ ]:
from sklearn.preprocessing import StandardScaler

# Sélectionnez les colonnes que vous souhaitez normaliser
colonnes_a_normaliser = ['lat', 'lon']

# Créez un objet StandardScaler
scaler = StandardScaler()

# Appliquez la standardisation aux données sélectionnées
df_train[colonnes_a_normaliser] = scaler.fit_transform(df_train[colonnes_a_normaliser])


df_train

,SNo,lat,lon,TMQ,U850,V850,UBOT,VBOT,QREFHT,PS,...,T200,T500,PRECT,TS,TREFHT,Z1000,Z200,ZBOT,time,Label
0,1,1.075740,0.139579,78.909431,-58.805229,36.200672,-58.260475,-0.722955,0.022321,97497.79688,...,227.119232,273.045563,1.390000e-05,302.350861,300.026764,66.339836,12400.22754,66.241585,20031024,1
1,2,1.075740,0.139579,78.909431,-58.805229,36.200672,-58.260475,-0.722955,0.022321,97497.79688,...,227.119232,273.045563,1.390000e-05,302.350861,300.026764,66.339836,12400.22754,66.241585,20031024,1
2,3,1.065495,0.139579,80.641357,-42.340290,58.060246,-56.400234,26.484743,0.022204,96611.60156,...,229.172897,273.580810,1.440000e-05,302.350861,299.798828,66.165573,12371.33203,66.165268,20031024,1
3,4,1.065495,0.139579,80.641357,-42.340290,58.060246,-56.400234,26.484743,0.022204,96611.60156,...,229.172897,273.580810,1.440000e-05,302.350861,299.798828,66.165573,12371.33203,66.165268,20031024,1
4,5,1.075740,0.147192,76.891205,-45.996342,42.691631,-48.993065,10.246445,0.022328,98168.55469,...,224.642563,272.152283,9.890000e-06,302.462708,300.160187,66.880089,12386.88574,66.275246,20031024,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44755,44756,0.717160,-0.378131,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1
44756,44757,0.717160,-0.378131,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,0
44757,44758,0.717160,-0.378131,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1
44758,44759,0.717160,-0.378131,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1
44759,44760,0.717160,-0.378131,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1

In [ ]:
df_train.describe()

,SNo,lat,lon,TMQ,U850,V850,UBOT,VBOT,QREFHT,PS,...,T200,T500,PRECT,TS,TREFHT,Z1000,Z200,ZBOT,time,Label
count,44760.000000,4.476000e+04,4.476000e+04,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,...,44760.000000,44760.000000,4.476000e+04,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,4.476000e+04,44760.000000
mean,22380.500000,-3.047904e-17,4.876647e-16,34.621980,-0.609818,-0.017271,-2.138797,-0.808013,0.014375,101553.676510,...,216.829335,264.355844,4.580801e-08,298.344652,296.923570,135.521651,12290.118668,65.384474,2.001878e+07,0.387332
std,12921.243361,1.000011e+00,1.000011e+00,12.765972,6.866391,4.307206,6.059180,4.786933,0.003951,544.619301,...,2.295840,3.463063,2.448857e-07,3.763268,3.998874,42.355824,129.311333,1.035777,3.169958e+04,0.764119
min,1.000000,-1.229417e+00,-9.795882e-01,6.960679,-58.805229,-26.216906,-58.260475,-20.760452,0.004364,96611.601560,...,208.824249,249.146011,-4.400000e-23,289.330750,285.426666,63.335205,11718.249020,62.433594,1.996061e+07,0.000000
25%,11190.750000,-9.451146e-01,-6.674396e-01,23.906342,-5.520361,-2.379751,-6.568208,-3.897676,0.011261,101161.437500,...,215.463791,262.966995,1.410000e-14,295.959228,294.304199,102.716108,12230.382810,64.672365,2.000091e+07,0.000000
50%,22380.500000,-4.098058e-02,-3.933579e-01,34.779505,-1.707679,0.148625,-2.701227,-0.855717,0.014613,101528.492200,...,217.109589,265.177933,5.210000e-09,298.752502,297.352692,133.820953,12319.832030,65.482857,2.001093e+07,0.000000
75%,33570.250000,1.078302e+00,1.928723e-01,44.321056,3.546206,2.326534,1.663309,2.034851,0.017949,101873.328100,...,218.367691,266.811386,3.030000e-08,301.767212,300.476807,161.562851,12388.112300,66.329466,2.003072e+07,0.000000
max,44760.000000,1.178192e+00,2.073377e+00,80.641357,32.277344,58.060246,30.215387,31.106283,0.022366,103996.953100,...,229.172897,273.580810,1.440000e-05,303.869812,304.364197,328.123688,12495.289060,67.131653,2.009102e+07,2.000000